#!/bin/bash
# Usage: ./commit.sh "Your commit message"

if [ -z "$1" ]; then
  echo "Error: Commit message required."
  echo "Usage: ./commit.sh \"Your commit message\""
  exit 1
fi

# Change directory to repo root
cd "$(dirname "$0")/.." || exit 1  # assumes this is one level below root

git config user.name "Gytis Kupcinskas"
git config user.email "gytiskupcinskas0@gmail.com"

git add .
git commit -m "$1"

